---
  app: 
    port: 8080

  layout: "nupic"
  refresh_rate: 180
  repos_url: "http://numenta.org/resources/repos.yaml"

  monitors:

    repo_status:
      type: repo_status

    latest_issues:
      type: latest_issues
      refresh_rate: 600

    running_builds:
      type: running_builds
      refresh_rate: 60

#    nupic_travis_latest:
#      type: "travis_latest"
#      options:
#        organization: "numenta"
#        repository: "nupic"

    # experiments_travis_latest:
    #   type: "travis_latest"
    #   options:
    #     organization: "numenta"
    #     repository: "experiments"

    tools_travis_latest:
      type: "travis_latest"
      options:
        organization: "numenta"
        repository: "nupic.tools"

    nupic_travis_builds:
      type: "travis_builds"
      options:
        pull_requests: false
        organization: "numenta"
        repository: "nupic"

    nupic_travis_pr_builds:
      type: "travis_builds"
      options:
        pull_requests: true
        organization: "numenta"
        repository: "nupic"

#    nupic_core_travis_latest:
#      type: "travis_latest"
#      options:
#        organization: "numenta"
#        repository: "nupic.core"

    nupic_core_travis_builds:
      type: "travis_builds"
      options:
        pull_requests: false
        organization: "numenta"
        repository: "nupic.core"

    nupic_core_travis_pr_builds:
      type: "travis_builds"
      options:
        pull_requests: true
        organization: "numenta"
        repository: "nupic.core"

    github_status:
      type: "github_status"

    travis_status:
      type: "travis_status"

#    issues_status:
#      type: "issues_status"

    numenta_org_status:
      type: "http_status"
      options:
        name: "numenta.org"
        url: "http://numenta.org"

    nupic_doc_build_status:
      type: "doxygen_build"
      options:
        name: "nupic"
        url: "http://numenta.org/docs/nupic"

    nupic_core_doc_build_status:
      type: "doxygen_build"
      options:
        name: "nupic.core"
        url: "http://numenta.org/docs/nupic.core"

#    nupic_pr_report:
#      type: "pr_report"
#      refresh_rate: 600
