---
  app: 
    port: 8080
  layout: 'nupic'
  monitors: 
    nupic_travis_latest: 
      type: "travis_latest"
      options: 
        organization: "numenta"
        repository: "nupic"
    tools_travis_latest: 
      type: "travis_latest"
      options: 
        organization: "numenta"
        repository: "nupic.tools"
    nupic_travis_builds: 
      type: "travis_builds"
      options: 
        organization: "numenta"
        repository: "nupic"
    github_status:
      type: "github_status"
